version: '3.3'

services:
  remitano-funny-movies-backend:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: remitano-funny-movies-backend
    restart: always
    env_file: ../.env.${NODE_ENV}
    environment:
      - APP_NAME=$APP_NAME
      - APP_ENV=$APP_ENV
      - APP_KEY=$APP_KEY
      - APP_DEBUG=$APP_DEBUG
      - APP_URL=$APP_URL
      - REDIRECT_HTTPS=$REDIRECT_HTTPS

      - NODE_ENV=$NODE_ENV
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DB=$MYSQL_DB
      - MYSQL_PORT=$MYSQL_PORT
      - MYSQL_HOST=$MYSQL_HOST
      - DATABASE_URL=$DATABASE_URL

      # nginx-proxy
      - VIRTUAL_HOST=$ADMIN_API_HOST
      - VIRTUAL_NETWORK=$VIRTUAL_NETWORK
      - VIRTUAL_PORT=$VIRTUAL_PORT
      - LETSENCRYPT_HOST=$LETSENCRYPT_ADMIN_API_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
    ports:
      - 3000:3000
      - 3003:3003

    volumes:
      - remitano-funny-movies-backend:/usr/src/app

networks:
  default:
    external:
      name: $DOCKER_NETWORK

volumes:
  remitano-funny-movies-backend:
    driver_opts:
      type: none
      device: $APP_VOLUME_CODE_MOUNT_PATH
      o: bind,uid=1000,gid=1000,groups=1000